#define DEVICE_ID "AB-DOR"
#define HARDWARE_NAME "AB-DOR"
#define DEVICE_NAME "AB-SmartHouse Electric Door Drive"

#define INFO_LED_PIN 11
#define INFO_LED_PIN_ACTIVE_ON HIGH
#define PROG_LED_PIN 10
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 9
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING

#define KNX_UART_TX_PIN 12
#define KNX_UART_RX_PIN 13
#define SAVE_INTERRUPT_PIN 0

#define MAIN_PWR_PIN 26
#define MAIN_PWR_THRESHOLD 500
#define MAIN_PWR_THRESHOLD_MARGIN 50
#define MAIN_TST_PIN 27
#define MAIN_TST_THRESHOLD 500
#define MAIN_TST_THRESHOLD_MARGIN 50
#define MAIN_MLD_PIN 18
#define MAIN_MLD_ACTIVE HIGH
#define MAIN_NSK_PIN 19
#define MAIN_HSK_PIN 17
#define MAIN_HSK_NSK_ACTIVE LOW
#define MAIN_LCK_PIN 16
#define MAIN_LCK_ACTIVE HIGH
#define MAIN_SIGNAL_LENGTH 100

#define DOOR_SENSOR_PWR_PIN 23
#define DOOR_SENSOR_PWR_ACTIVE HIGH
#define DOOR_OPEN_PIN 29
#define DOOR_CLOSED_PIN 28
#define DOOR_SENSOR_THRESHOLD 540 // threshold with 220 Ohm resistor (off is 580-590)
#define DOOR_SENSOR_THRESHOLD_MARGIN 10
#define DOOR_OPEN_MIN 3000
#define DOOR_STATE_CHANGED_TIMEOUT 3000

#define LOCK_PIN 25
#define LOCK_ACTIVE HIGH
#define LOCK_REQUEST_MLD_TIMEOUT 3000

#define SENSOR_TST_PIN 24
#define SENSOR_TST_ACTIVE HIGH
#define SENSOR_INSIDE_RAD_PIN 5
#define SENSOR_INSIDE_AIR_PIN 6
#define SENSOR_OUTSIDE_RAD_PIN 7
#define SENSOR_OUTSIDE_AIR_PIN 8
#define SENSOR_RAD_ACTIVE LOW
#define SENSOR_AIR_ACTIVE HIGH

#define EXT_I2C_BUS Wire
#define EXT_I2C_SDA 20
#define EXT_I2C_SCL 21
#define EXT1_TCA9555_ADR 0x20
#define EXT2_TCA9555_ADR 0x21
#define EXT2_KNX_PRG_SWITCH_PIN TCA_P13
#define EXT2_KNX_PRG_SWITCH_DEBOUNCE 250
#define EXT2_KNX_PRG_SWITCH_ACTIVE LOW